# Generated by Django 2.0.13 on 2019-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='number_of_passes',
            field=models.IntegerField(default=0),
        ),
    ]
