# Generated by Django 2.0.13 on 2019-09-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='test',
        ),
    ]
