# Generated by Django 2.0.13 on 2019-09-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20190922_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='test',
            name='number_of_passes',
        ),
    ]
